name: Run Java Selenium Online

on:
  push:
    branches: [ main ]
  workflow_dispatch:     # This adds the manual trigger button

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Run Selenium Test Cases
      run: mvn test

    - name: Upload Error Screenshots
      uses: actions/upload-artifact@v4
      if: always()  # Ensures this runs even if the 'mvn test' step fails
      with:
        name: selenium-screenshots
        path: target/surefire-reports/error-screenshot.png
        if-no-files-found: ignore  # Keeps the build clean if the test passes without errors
